kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
        - role: control-plane
          extraPortMappings:
                  - containerPort: 30010
                    hostPort: 8080
        - role: worker
        - role: worker
        - role: worker