---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.2
    app.quarkus.io/commit-id: 64b34a7ae83d89b81dfbac6014b7b70d0b5deedc
    app.quarkus.io/vcs-uri: https://github.com/utopios/cloud_native_mars.git
    app.quarkus.io/build-timestamp: 2024-03-20 - 09:29:43 +0000
  labels:
    app.kubernetes.io/name: contact-app
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: contact-app
spec:
  ports:
    - name: http
      nodePort: 30010
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: contact-app
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.2
    app.quarkus.io/commit-id: 64b34a7ae83d89b81dfbac6014b7b70d0b5deedc
    app.quarkus.io/vcs-uri: https://github.com/utopios/cloud_native_mars.git
    app.quarkus.io/build-timestamp: 2024-03-20 - 09:29:43 +0000
  labels:
    app.kubernetes.io/name: contact-app
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: contact-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/name: contact-app
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.8.2
        app.quarkus.io/commit-id: 64b34a7ae83d89b81dfbac6014b7b70d0b5deedc
        app.quarkus.io/vcs-uri: https://github.com/utopios/cloud_native_mars.git
        app.quarkus.io/build-timestamp: 2024-03-20 - 09:29:43 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: contact-app
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/ihababadi/contact-app:latest
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: contact-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
