apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: tp-kubernetes
spec:
## La configuration du replicaset
  replicas: 2
  selector:
    matchLabels:
      app: tp-vote
  template:  
  ## La configuration du pod  
    metadata:
      name: tp-vote
      namespace: tp-kubernetes
      labels:
        app: tp-vote
    spec:
    # La liste des conteneurs du pod
      containers:
        - name: vote
          image: tp-vote
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"